const fs = require('fs');
let code = fs.readFileSync('src/js/modules/aspects.js', 'utf8');

const safeMathCode = `// Calculator tool for basic math\\n// Usage: executeTool({ expression: "2 + 2" })\\nfunction executeTool(args) {\\n    const expr = args.expression || args;\\n    if (!expr) return "No expression provided.";\\n    const evaluate = (expression) => {\\n        const tokens = expression.match(/\\\\d+\\\\.\\\\d+|\\\\d+|[-+*/()]/g) || [];\\n        if (tokens.length === 0) throw new Error("No valid tokens found");\\n        let pos = 0;\\n        const parseFactor = () => {\\n            if (pos >= tokens.length) throw new Error("Unexpected end of expression");\\n            let sign = 1;\\n            while (tokens[pos] === '+' || tokens[pos] === '-') {\\n                if (tokens[pos++] === '-') sign = -sign;\\n            }\\n            if (pos >= tokens.length) throw new Error("Unexpected end of expression");\\n            if (tokens[pos] === '(') {\\n                pos++;\\n                const val = parseExpression();\\n                if (pos >= tokens.length || tokens[pos] !== ')') throw new Error("Missing closing parenthesis");\\n                pos++;\\n                return sign * val;\\n            }\\n            const val = parseFloat(tokens[pos++]);\\n            if (isNaN(val)) throw new Error("Invalid number");\\n            return sign * val;\\n        };\\n        const parseTerm = () => {\\n            let val = parseFactor();\\n            while (pos < tokens.length && (tokens[pos] === '*' || tokens[pos] === '/')) {\\n                const op = tokens[pos++];\\n                const nextVal = parseFactor();\\n                if (op === '*') val *= nextVal;\\n                else val /= nextVal;\\n            }\\n            return val;\\n        };\\n        const parseExpression = () => {\\n            let val = parseTerm();\\n            while (pos < tokens.length && (tokens[pos] === '+' || tokens[pos] === '-')) {\\n                const op = tokens[pos++];\\n                const nextVal = parseTerm();\\n                if (op === '+') val += nextVal;\\n                else val -= nextVal;\\n            }\\n            return val;\\n        };\\n        const result = parseExpression();\\n        if (pos < tokens.length) throw new Error("Unexpected tokens at end of expression");\\n        return result;\\n    };\\n    try {\\n        if (/^[0-9+\\\\\\-/*().\\\\s]+$/.test(expr)) {\\n            const res = evaluate(expr);\\n            return { result: res };\\n        }\\n        return { error: "Invalid math expression characters." };\\n    } catch (e) {\\n        return { error: e.message };\\n    }\\n}`;

// Replace the Calculate tool
code = code.replace(/code:\s*`\/\/ Calculator tool for basic math\\n\/\/ Usage: executeTool\(\{ expression: "2 \+ 2" \}\)\\nfunction executeTool\(args\).*?catch \(e\) \{\\n        return \{ error: e\.message \};\\n    \}\\n\}`/s, `code: \`${safeMathCode}\``);

fs.writeFileSync('src/js/modules/aspects.js', code);
