import { state } from './modules/state.js';
window.state = state;
import { saveKnowledgeFile } from './modules/db.js';
import { acceptCreateAspect } from './modules/aspects.js';
import { loadAspectFile } from './modules/zip.js';
import { getLakesideSageIcon } from './modules/aspects.js';
import { sendAIRequest } from './modules/tools.js';
import { saveAspectToFile } from './modules/zip.js';
import { updateAspectData } from './modules/aspects.js';
import { uploadKnowledgeFiles } from './modules/db.js';
import { getKnowledgeFilesText } from './modules/db.js';
import { showEditorView } from './modules/ui.js';
import { addSystemLog } from './modules/tools.js';
import { loadDefaultAspects } from './modules/aspects.js';
import { openSettings } from './modules/settings.js';
import { executeJavaScriptTool } from './modules/tools.js';
import { renderPresetBgGrid } from './modules/ui.js';
import { markChangesUnsaved } from './modules/ui.js';
import { applyAspectBackground } from './modules/ui.js';
import { markChangesSaved } from './modules/state.js';
import { renderAspectList } from './modules/aspects.js';
import { selectPresetBackground } from './modules/ui.js';
import { saveSettings } from './modules/settings.js';
import { toggleToolsDropdown } from './modules/chat.js';
import { onModelSelectDropdown } from './modules/settings.js';
import { showChatView } from './modules/ui.js';
import { processAIResponseAndTools } from './modules/tools.js';
import { getGenericIcon } from './modules/aspects.js';
import { closeWelcomeModal } from './modules/ui.js';
import { onProviderSelect } from './modules/settings.js';
import { init } from './modules/init.js';
import { fetchModelsIfPossible } from './modules/settings.js';
import { createNewAspect } from './modules/aspects.js';
import { uploadTools } from './modules/ui.js';
import { deleteCurrentAspect } from './modules/aspects.js';
import { uploadIcon } from './modules/ui.js';
import { saveAspectsToLocalStorage } from './modules/state.js';
import { uploadCreateIcon } from './modules/aspects.js';
import { updateSystemLog } from './modules/tools.js';
import { nextPage } from './modules/ui.js';
import { cancelCreateAspect } from './modules/aspects.js';
import { selectAspect } from './modules/aspects.js';
import { escapeHtml } from './modules/chat.js';
import { sendMessage } from './modules/tools.js';
import { renderChatMessages } from './modules/chat.js';
import { insertToolTag } from './modules/tools.js';
import { uploadBackground } from './modules/ui.js';
import { getCurrentAspect } from './modules/aspects.js';
import { editMessage, deleteMessage, regenerateMessage } from './modules/chat.js';
import { abortAIRequest } from './modules/tools.js';

window.getLakesideSageIcon = getLakesideSageIcon;
window.loadDefaultAspects = loadDefaultAspects;
window.getGenericIcon = getGenericIcon;
window.createNewAspect = createNewAspect;
window.uploadCreateIcon = uploadCreateIcon;
window.acceptCreateAspect = acceptCreateAspect;
window.cancelCreateAspect = cancelCreateAspect;
window.selectAspect = selectAspect;
window.getCurrentAspect = getCurrentAspect;
window.updateAspectData = updateAspectData;
window.deleteCurrentAspect = deleteCurrentAspect;
window.renderAspectList = renderAspectList;
window.escapeHtml = escapeHtml;
window.renderChatMessages = renderChatMessages;
window.editMessage = editMessage;
window.deleteMessage = deleteMessage;
window.regenerateMessage = regenerateMessage;
window.abortAIRequest = abortAIRequest;
window.toggleToolsDropdown = toggleToolsDropdown;
window.init = init;
window.openSettings = openSettings;
window.saveSettings = saveSettings;
window.onProviderSelect = onProviderSelect;
window.onModelSelectDropdown = onModelSelectDropdown;
window.saveAspectsToLocalStorage = saveAspectsToLocalStorage;
window.markChangesSaved = markChangesSaved;
window.insertToolTag = insertToolTag;
window.addSystemLog = addSystemLog;
window.updateSystemLog = updateSystemLog;
window.markChangesUnsaved = markChangesUnsaved;
window.nextPage = nextPage;
window.closeWelcomeModal = closeWelcomeModal;
window.showEditorView = showEditorView;
window.showChatView = showChatView;
window.uploadIcon = uploadIcon;
window.uploadTools = uploadTools;
window.applyAspectBackground = applyAspectBackground;
window.renderPresetBgGrid = renderPresetBgGrid;
window.selectPresetBackground = selectPresetBackground;
window.uploadBackground = uploadBackground;
window.saveKnowledgeFile = saveKnowledgeFile;
window.getKnowledgeFilesText = getKnowledgeFilesText;
window.uploadKnowledgeFiles = uploadKnowledgeFiles;
window.fetchModelsIfPossible = fetchModelsIfPossible;
window.executeJavaScriptTool = executeJavaScriptTool;
window.processAIResponseAndTools = processAIResponseAndTools;
window.sendAIRequest = sendAIRequest;
window.sendMessage = sendMessage;
window.saveAspectToFile = saveAspectToFile;
window.loadAspectFile = loadAspectFile;

document.addEventListener('DOMContentLoaded', init);
