#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

BIN_DIR="${HOME}/.local/bin"
APPS_DIR="${HOME}/.local/share/applications"
DESKTOP_DIR="$(xdg-user-dir DESKTOP 2>/dev/null || echo "${HOME}/Desktop")"
ICONS_DIR="${HOME}/.local/share/icons/hicolor/scalable/apps"
LAUNCHER="${BIN_DIR}/aspect-chat"

echo "=== Installing Desktop Integration for Aspect Chat ==="
echo "Repository path: ${REPO_DIR}"

mkdir -p "${BIN_DIR}" "${APPS_DIR}" "${ICONS_DIR}" "${DESKTOP_DIR}"

# ---------------------------------------------------------------------------
# Launcher wrapper: serves the built app on http://localhost and opens it.
#
# The old integration pointed a .desktop entry at
#   xdg-open https://raw.githubusercontent.com/.../dist/index.html
# which cannot work: raw.githubusercontent.com sends text/plain (the browser
# shows source, never executes it), and the Vite bundle's asset URLs would not
# resolve from there anyway. This runs the real build locally instead.
# ---------------------------------------------------------------------------
echo ""
echo "Writing launcher: ${LAUNCHER}"

cat > "${LAUNCHER}" <<'EOF'
#!/usr/bin/env bash
# Aspect Chat launcher — generated by desktop/aspect-chat-install.sh
# Serves the local production build on http://localhost and opens a browser.
set -euo pipefail

REPO_DIR="__REPO_DIR__"
PORT="${ASPECT_CHAT_PORT:-43110}"
URL="http://localhost:${PORT}/"

STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/aspect-chat"
PID_FILE="${STATE_DIR}/server.pid"
LOG_FILE="${STATE_DIR}/server.log"
mkdir -p "${STATE_DIR}"

port_open() { (exec 3<>"/dev/tcp/127.0.0.1/${PORT}") 2>/dev/null; }

server_running() {
    [ -f "${PID_FILE}" ] || return 1
    local pid
    pid="$(cat "${PID_FILE}" 2>/dev/null || true)"
    [ -n "${pid}" ] && kill -0 "${pid}" 2>/dev/null
}

server_healthy() {
    if command -v curl >/dev/null 2>&1; then
        local code
        code="$(curl -s -o /dev/null -w "%{http_code}" --connect-timeout 1 "http://127.0.0.1:${PORT}/" 2>/dev/null || true)"
        [ "${code}" = "200" ] || [ "${code}" = "304" ]
    else
        port_open
    fi
}

stop_server() {
    if command -v systemctl >/dev/null 2>&1 && systemctl --user is-active --quiet aspect-chat 2>/dev/null; then
        systemctl --user stop aspect-chat 2>/dev/null || true
    fi
    if [ -f "${PID_FILE}" ]; then
        local pid
        pid="$(cat "${PID_FILE}" 2>/dev/null || true)"
        if [ -n "${pid}" ]; then
            kill -TERM "${pid}" 2>/dev/null || true
            for _ in $(seq 1 20); do
                kill -0 "${pid}" 2>/dev/null || break
                sleep 0.2
            done
            kill -KILL "${pid}" 2>/dev/null || true
        fi
        rm -f "${PID_FILE}"
    fi
    if port_open && command -v fuser >/dev/null 2>&1; then
        fuser -k "${PORT}/tcp" 2>/dev/null || true
        sleep 0.2
    fi
}

build_app() {
    echo "aspect-chat: building app (dist/ missing or --rebuild)…" >&2
    ( cd "${REPO_DIR}" && npm run build ) >>"${LOG_FILE}" 2>&1 || {
        echo "aspect-chat: build failed — see ${LOG_FILE}" >&2
        exit 1
    }
}

start_server() {
    [ -f "${REPO_DIR}/dist/index.html" ] || build_app
    if server_healthy; then
        return 0
    fi
    stop_server

    cd "${REPO_DIR}"
    local -a server_cmd
    if [ -x "${REPO_DIR}/node_modules/.bin/vite" ]; then
        server_cmd=("${REPO_DIR}/node_modules/.bin/vite" preview --host 127.0.0.1 --port "${PORT}" --strictPort)
    else
        server_cmd=(python3 -m http.server "${PORT}" --bind 127.0.0.1 --directory "${REPO_DIR}/dist")
    fi

    if command -v systemd-run >/dev/null 2>&1 && systemctl --user is-system-running >/dev/null 2>&1; then
        systemd-run --user --unit=aspect-chat \
            --working-directory="${REPO_DIR}" \
            --setenv=PATH="${PATH}" \
            --description="Aspect Chat Local Server" \
            "${server_cmd[@]}" >>"${LOG_FILE}" 2>&1
    else
        nohup setsid "${server_cmd[@]}" < /dev/null >>"${LOG_FILE}" 2>&1 &
        echo $! > "${PID_FILE}"
        disown 2>/dev/null || true
    fi

    for _ in $(seq 1 50); do
        server_healthy && return 0
        sleep 0.2
    done
    echo "aspect-chat: server did not start on port ${PORT} — see ${LOG_FILE}" >&2
    return 1
}

case "${1:-}" in
    --stop)
        stop_server
        echo "aspect-chat: stopped."
        exit 0
        ;;
    --status)
        if server_healthy; then
            echo "aspect-chat: running on ${URL}"
        elif port_open; then
            echo "aspect-chat: port ${PORT} is open, but not responding with HTTP 200"
        else
            echo "aspect-chat: not running"
        fi
        exit 0
        ;;
    --rebuild)
        stop_server
        build_app
        ;;
    --help|-h)
        echo "Usage: aspect-chat [--stop | --status | --rebuild | --help]"
        echo "Env:   ASPECT_CHAT_PORT (default 43110)"
        exit 0
        ;;
esac

start_server
xdg-open "${URL}" >/dev/null 2>&1 \
    || echo "aspect-chat: open ${URL} in your browser." >&2
EOF

sed -i "s#__REPO_DIR__#${REPO_DIR}#g" "${LAUNCHER}"
chmod +x "${LAUNCHER}"

# ---------------------------------------------------------------------------
# Desktop entry — always rewritten so a stale Exec never lingers.
# ---------------------------------------------------------------------------
echo ""
echo "Writing desktop entry: ${APPS_DIR}/aspect-chat.desktop"

cat > "${APPS_DIR}/aspect-chat.desktop" <<EOF
[Desktop Entry]
Version=1.0
Type=Application
Name=Aspect Chat
GenericName=Custom AI Personas Studio
Comment=Create Aspects out of API LLM inference calls
Exec=${LAUNCHER}
Icon=aspect-chat
Path=${REPO_DIR}
Terminal=false
StartupNotify=false
Categories=Development;Utility;
Keywords=aspect-chat;ai;persona;llm;api;
Actions=Stop;

[Desktop Action Stop]
Name=Stop the local server
Exec=${LAUNCHER} --stop
EOF
chmod +x "${APPS_DIR}/aspect-chat.desktop"

if [ -d "${DESKTOP_DIR}" ]; then
    echo "Writing desktop shortcut: ${DESKTOP_DIR}/aspect-chat.desktop"
    cp -f "${APPS_DIR}/aspect-chat.desktop" "${DESKTOP_DIR}/aspect-chat.desktop"
    chmod +x "${DESKTOP_DIR}/aspect-chat.desktop"
    if command -v gio >/dev/null 2>&1; then
        gio set "${DESKTOP_DIR}/aspect-chat.desktop" metadata::trusted true 2>/dev/null || true
    fi
fi

echo ""
echo "Writing icon: ${ICONS_DIR}/aspect-chat.svg"
cat > "${ICONS_DIR}/aspect-chat.svg" <<'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" width="64" height="64">
  <circle cx="32" cy="32" r="30" fill="#597d53"/>
  <circle cx="32" cy="32" r="30" fill="none" stroke="#3d2f26" stroke-width="4"/>
  <path d="M14 44 L32 18 L50 44 Z" fill="#cc6d4e"/>
  <circle cx="32" cy="24" r="7" fill="#f7edd9"/>
</svg>
EOF

if command -v gtk-update-icon-cache >/dev/null 2>&1; then
    echo "Updating icon cache…"
    gtk-update-icon-cache -f -t "${HOME}/.local/share/icons/hicolor" 2>/dev/null || true
fi

if command -v update-desktop-database >/dev/null 2>&1; then
    echo ""
    echo "Updating desktop database…"
    update-desktop-database "${APPS_DIR}" 2>/dev/null || true
fi

echo ""
echo "======================================================"
echo " Aspect Chat desktop integration complete!"
echo "  • Desktop:  Double-click 'Aspect Chat' on your desktop"
echo "  • Menu:     Budgie App Menu / Runner → 'Aspect Chat'"
echo "  • Terminal: aspect-chat            (serve + open browser)"
echo "              aspect-chat --status"
echo "              aspect-chat --stop"
echo "              aspect-chat --rebuild"
echo "  • Serves the local build on http://localhost:43110"
echo "    (http, not https — required for local-model calls)"
if ! printf '%s' ":${PATH}:" | grep -q ":${BIN_DIR}:"; then
    echo ""
    echo "  NOTE: ${BIN_DIR} is not on your PATH; the menu entry still"
    echo "        works, but the 'aspect-chat' command will not until you add it."
fi
echo "======================================================"
